export enum REPORT_TYPES {
  INCIDENT = "INCIDENT",
  PRESENCE = "PRESENCE",
  CONFLICT = "CONFLICT",
}

export enum IMPORTANCE_LEVELS {
  ALERT = "ALERT",
  INFO = "INFO",
  //WARNING = "",
  CRITICAL = "CRITICAL",
  Emergency = "EMERGENCY", // dark red
  Alert = "Alert", // red
  Critical = "Critical", // orange
  //Warning = "", // yellow
  Problem /*[Error]*/ = "Problem", // orange pink
  Warning = "WARNING", // violet
  Notice = "Notice", // blue
  Information = "Information", // green
  Debug = "Debug", // grey
}

export enum URGENCY_LEVELS {
  IMMEDIATE = "IMMEDIATE",
  EXPECTED = "EXPECTED",
  FUTURE = "FUTURE",
  PAST = "PAST",
  UNKNOWN = "UNKNOWN",
}
export enum CERTAINTY_LEVELS {
  OBSERVED = "OBSERVED",
  LIKELY = "LIKELY",
  POSSIBLE = "POSSIBLE",
  UNLIKELY = "UNLIKELY",
  UNKNOWN = "UNKNOWN",
}
export enum SENSITIVITY_LEVELS {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}
export enum PRIVACY_LEVELS {
  PUBLIC = "PUBLIC",
  REGISTERED_USERS = "REGISTERED_USERS",
  MODERATORS = "MODERATORS",
  ADMINS = "ADMINS",
  PRIVATE = "PRIVATE",
}
export enum VERIFICATION_LEVELS {
  UNVERIFIED = "UNVERIFIED",
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  FLAGGED = "FLAGGED",
}
export enum STATUS_LEVELS {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
  REOPENED = "REOPENED",
  ON_HOLD = "ON_HOLD",
  CANCELLED = "CANCELLED",
  ARCHIVED = "ARCHIVED",
}
export enum PRIORITY_LEVELS {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}
export enum SEVERITY_LEVELS {
  MINOR = "MINOR",
  MODERATE = "MODERATE",
  SEVERE = "SEVERE",
  CRITICAL = "CRITICAL",
  EXTREME = "EXTREME",
  CATASTROPHIC = "CATASTROPHIC",
}
export enum CONFIRMATION_LEVELS {
  UNCONFIRMED = "UNCONFIRMED",
  CONFIRMED = "CONFIRMED",
  DISMISSED = "DISMISSED",
  UNDER_INVESTIGATION = "UNDER_INVESTIGATION",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
  RESOLVED = "RESOLVED",
}
export enum ANIMAL_ALERT_LEVELS {
  WATCH = "WATCH",
  ADVISORY = "ADVISORY",
  WARNING = "WARNING",
  EMERGENCY = "EMERGENCY",
  ALERT = "ALERT",
  CRITICAL = "CRITICAL",
}
export enum ANIMAL_CONSERVATION_STATUS {
  LEAST_CONCERN = "LEAST_CONCERN",
  NEAR_THREATENED = "NEAR_THREATENED",
  VULNERABLE = "VULNERABLE",
  ENDANGERED = "ENDANGERED",
  CRITICALLY_ENDANGERED = "CRITICALLY_ENDANGERED",
  EXTINCT_IN_WILD = "EXTINCT_IN_WILD",
  EXTINCT = "EXTINCT",
  DATA_DEFICIENT = "DATA_DEFICIENT",
  NOT_EVALUATED = "NOT_EVALUATED",
}
export enum VICTIM_STATUS_INTERNAL {
  SAFE = "SAFE",
  INJURED = "INJURED",
  MISSING = "MISSING",
  DECEASED = "DECEASED",
  UNKNOWN = "UNKNOWN",
}

export enum VICTIM_STATUS_PUBLIC {
  SAFE = "SALVAT",
  INJURED = "TRATAT",
  MISSING = "DISPARUT",
  DECEASED = "DECEDAT",
  UNDER_INVESTIGATION = "IN_CURS_DE_INVESTIGARE",

  UNKNOWN = "NECUNOSCUT",
}

export enum RESCUE_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",

  SUCCESSFUL = "SUCCESSFUL",
  UNSUCCESSFUL = "UNSUCCESSFUL",
  ON_HOLD = "ON_HOLD",
  SCHEDULED = "SCHEDULED",
  RESCHEDULED = "RESCHEDULED",
  ABANDONED = "ABANDONED",
  ESCALATED = "ESCALATED",
  DEESCALATED = "DEESCALATED",
  UNDER_REVIEW = "UNDER_REVIEW",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
}
export enum ANIMAL_BEHAVIOR {
  NORMAL = "NORMAL",
  AGGRESSIVE = "AGGRESSIVE",
  FEARFUL = "FEARFUL",
  INJURED = "INJURED",
  SICK = "SICK",
  MATING = "MATING",
  NESTING = "NESTING",
  FORAGING = "FORAGING",
  MIGRATING = "MIGRATING",
  OTHER = "OTHER",
}

export enum ANIMAL_MEDICAL_CONDITION {
  HEALTHY = "HEALTHY",
  INJURED = "INJURED",
  SICK = "SICK",
  RECOVERING = "RECOVERING",
  CRITICAL = "CRITICAL",
  DECEASED = "DECEASED",
  UNKNOWN = "UNKNOWN",
  OTHER = "OTHER",
}

export enum EVENT_TYPES {
  SIGHTING = "SIGHTING",
  OTHER = "OTHER",
  LOST_FOUND = "LOST_FOUND",
  POACHING = "POACHING",
  NEST = "NEST",
  HABITAT = "HABITAT",
  RESCUE = "RESCUE",
  RESEARCH = "RESEARCH",
  CONSERVATION = "CONSERVATION",
  HUMAN_WILDLIFE_INTERACTION = "HUMAN_WILDLIFE_INTERACTION",
  MIGRATION = "MIGRATION",
  OTHER_WILDLIFE = "OTHER_WILDLIFE",
  DOMESTIC_ANIMAL = "DOMESTIC_ANIMAL",
  PLANT = "PLANT",
  WATERBODY = "WATERBODY",
  ENVIRONMENTAL = "ENVIRONMENTAL",
  POLLUTION = "POLLUTION",
  WEATHER = "WEATHER",
  FIRE = "FIRE",
  LAND_USE_CHANGE = "LAND_USE_CHANGE",
  OTHER_ENVIRONMENTAL = "OTHER_ENVIRONMENTAL",
  GENERAL = "GENERAL",
  FEEDBACK = "FEEDBACK",
  SUGGESTION = "SUGGESTION",
  COMPLAINT = "COMPLAINT",
  APP_ISSUE = "APP_ISSUE",
  OTHER_REPORT = "OTHER_REPORT",
}

export enum ANIMAL_TYPES {
  MAMMAL = "MAMMAL",
  BIRD = "BIRD",
  REPTILE = "REPTILE",
  AMPHIBIAN = "AMPHIBIAN",
  FISH = "FISH",
  INSECT = "INSECT",
  ARACHNID = "ARACHNID",
  CRUSTACEAN = "CRUSTACEAN",
  MOLLUSK = "MOLLUSK",
  OTHER_INVERTEBRATE = "OTHER_INVERTEBRATE",
  DOMESTIC = "DOMESTIC",
  UNKNOWN = "UNKNOWN",
  OTHER = "OTHER",
}
export enum PLANT_TYPES {
  TREE = "TREE",
  SHRUB = "SHRUB",
  HERB = "HERB",
  GRASS = "GRASS",
  FUNGUS = "FUNGUS",
  ALGAE = "ALGAE",
  OTHER_PLANT = "OTHER_PLANT",
}
export enum ENVIRONMENT_TYPES {
  WATERBODY = "WATERBODY",
  POLLUTION = "POLLUTION",
  WEATHER = "WEATHER",
  FIRE = "FIRE",
  LAND_USE_CHANGE = "LAND_USE_CHANGE",
  OTHER_ENVIRONMENTAL = "OTHER_ENVIRONMENTAL",
}
export enum REPORT_CATEGORIES {
  ANIMAL = "ANIMAL",
  PLANT = "PLANT",
  ENVIRONMENT = "ENVIRONMENT",
  OTHER = "OTHER",
}
export enum OTHER_TYPES {
  GENERAL = "GENERAL",
  FEEDBACK = "FEEDBACK",
  SUGGESTION = "SUGGESTION",
  COMPLAINT = "COMPLAINT",
  APP_ISSUE = "APP_ISSUE",
  OTHER_REPORT = "OTHER_REPORT",
}
export enum ALL_TYPES {
  // Animal Types
  MAMMAL = "MAMMAL",
  BIRD = "BIRD",
  REPTILE = "REPTILE",
  AMPHIBIAN = "AMPHIBIAN",
  FISH = "FISH",
  INSECT = "INSECT",
  ARACHNID = "ARACHNID",
  CRUSTACEAN = "CRUSTACEAN",
  MOLLUSK = "MOLLUSK",
  OTHER_INVERTEBRATE = "OTHER_INVERTEBRATE",
  DOMESTIC = "DOMESTIC",
  UNKNOWN = "UNKNOWN",
  OTHER_ANIMAL = "OTHER_ANIMAL",

  // Plant Types
  TREE = "TREE",
  SHRUB = "SHRUB",
  HERB = "HERB",
  GRASS = "GRASS",
  FUNGUS = "FUNGUS",
  ALGAE = "ALGAE",
  OTHER_PLANT = "OTHER_PLANT",

  // Environment Types
  WATERBODY = "WATERBODY",
  POLLUTION = "POLLUTION",
  WEATHER = "WEATHER",
  FIRE = "FIRE",
  LAND_USE_CHANGE = "LAND_USE_CHANGE",
  OTHER_ENVIRONMENTAL = "OTHER_ENVIRONMENTAL",

  // Other Types
  GENERAL = "GENERAL",
  FEEDBACK = "FEEDBACK",
  SUGGESTION = "SUGGESTION",
  COMPLAINT = "COMPLAINT",
  APP_ISSUE = "APP_ISSUE",
  OTHER_REPORT = "OTHER_REPORT",
}
